# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print (np.__version__)
print (np.show_config())


2.5.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl.exe"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.9",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl.exe"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2025",
      "detection method": "pkgconfig",
      "include directory": "c:/Users/1tsth/anaconda3/envs/vscode101/Library/include",
      "lib directory": "c:/Users/1tsth/anaconda3/envs/vscode101/Library/lib",
      "

c:\Users\1tsth\anaconda3\envs\vscode101\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.random((2, 3, 5))



### 4. Print a.


In [5]:
print (a)


[[[0.91783783 0.10209428 0.27722253 0.37576339 0.03750169]
  [0.38159451 0.13520735 0.41378007 0.3586438  0.49676545]
  [0.64841796 0.21142818 0.1010664  0.36498854 0.60965375]]

 [[0.36386128 0.91183055 0.07390764 0.25996964 0.68685919]
  [0.36706994 0.46745292 0.82682509 0.0361916  0.72829926]
  [0.33392088 0.51776232 0.91066641 0.10905267 0.99656941]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
b = np.ones ((5, 2, 3))
b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 6. Print b.


In [8]:
print (b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
print(a.size == b.size)


True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
print (a.shape)
print (b.shape)
#You cannot add them because although the size is the same the shape is different (different numbers of rows and columns and blocks so they do not line up)

(2, 3, 5)
(5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [13]:
#a= 2,3,5
#   0,1,2

#b= 5,2,3
#   0,1,2
#c= 1,2,0

c = np.transpose(b, (1, 2, 0))
print (c.shape)

(2, 3, 5)


In [15]:
print (c.shape == a.shape)

True



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
print(d.shape)
print(d)
#the blocks, rows and columns all line up

(2, 3, 5)
[[[1.91783783 1.10209428 1.27722253 1.37576339 1.03750169]
  [1.38159451 1.13520735 1.41378007 1.3586438  1.49676545]
  [1.64841796 1.21142818 1.1010664  1.36498854 1.60965375]]

 [[1.36386128 1.91183055 1.07390764 1.25996964 1.68685919]
  [1.36706994 1.46745292 1.82682509 1.0361916  1.72829926]
  [1.33392088 1.51776232 1.91066641 1.10905267 1.99656941]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print (a)

print (d)
#we have added the 1s from c to the values in a



[[[0.91783783 0.10209428 0.27722253 0.37576339 0.03750169]
  [0.38159451 0.13520735 0.41378007 0.3586438  0.49676545]
  [0.64841796 0.21142818 0.1010664  0.36498854 0.60965375]]

 [[0.36386128 0.91183055 0.07390764 0.25996964 0.68685919]
  [0.36706994 0.46745292 0.82682509 0.0361916  0.72829926]
  [0.33392088 0.51776232 0.91066641 0.10905267 0.99656941]]]
[[[1.91783783 1.10209428 1.27722253 1.37576339 1.03750169]
  [1.38159451 1.13520735 1.41378007 1.3586438  1.49676545]
  [1.64841796 1.21142818 1.1010664  1.36498854 1.60965375]]

 [[1.36386128 1.91183055 1.07390764 1.25996964 1.68685919]
  [1.36706994 1.46745292 1.82682509 1.0361916  1.72829926]
  [1.33392088 1.51776232 1.91066641 1.10905267 1.99656941]]]



### 12. Multiply a and c. Assign the result to e.


In [28]:
e = (a * c)

print (e.shape)

print (e)


(2, 3, 5)
[[[0.91783783 0.10209428 0.27722253 0.37576339 0.03750169]
  [0.38159451 0.13520735 0.41378007 0.3586438  0.49676545]
  [0.64841796 0.21142818 0.1010664  0.36498854 0.60965375]]

 [[0.36386128 0.91183055 0.07390764 0.25996964 0.68685919]
  [0.36706994 0.46745292 0.82682509 0.0361916  0.72829926]
  [0.33392088 0.51776232 0.91066641 0.10905267 0.99656941]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
print (e)

print (a)

print (e == a)
#yes because the multiplyer was 1

[[[0.91783783 0.10209428 0.27722253 0.37576339 0.03750169]
  [0.38159451 0.13520735 0.41378007 0.3586438  0.49676545]
  [0.64841796 0.21142818 0.1010664  0.36498854 0.60965375]]

 [[0.36386128 0.91183055 0.07390764 0.25996964 0.68685919]
  [0.36706994 0.46745292 0.82682509 0.0361916  0.72829926]
  [0.33392088 0.51776232 0.91066641 0.10905267 0.99656941]]]
[[[0.91783783 0.10209428 0.27722253 0.37576339 0.03750169]
  [0.38159451 0.13520735 0.41378007 0.3586438  0.49676545]
  [0.64841796 0.21142818 0.1010664  0.36498854 0.60965375]]

 [[0.36386128 0.91183055 0.07390764 0.25996964 0.68685919]
  [0.36706994 0.46745292 0.82682509 0.0361916  0.72829926]
  [0.33392088 0.51776232 0.91066641 0.10905267 0.99656941]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [34]:
d_max = (np.max(d))

d_min = (np.min(d))

d_mean = (np.mean(d))



In [35]:
print(d_max)

print(d_min)

print(d_mean)

1.9965694074087876
1.0361915985972123
1.4340734836070057



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [ ]:
f = np.empty (d.shape)






### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:
f[d == d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_max] = 100

print (f)


[[[ 75.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 25.  75.  25.  25.  75.]
  [ 25.  75.  75.   0.  75.]
  [ 25.  75.  75.  25. 100.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print (d)


print (f) #yes this is correct

[[[1.91783783 1.10209428 1.27722253 1.37576339 1.03750169]
  [1.38159451 1.13520735 1.41378007 1.3586438  1.49676545]
  [1.64841796 1.21142818 1.1010664  1.36498854 1.60965375]]

 [[1.36386128 1.91183055 1.07390764 1.25996964 1.68685919]
  [1.36706994 1.46745292 1.82682509 1.0361916  1.72829926]
  [1.33392088 1.51776232 1.91066641 1.10905267 1.99656941]]]
[[[ 75.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 25.  75.  25.  25.  75.]
  [ 25.  75.  75.   0.  75.]
  [ 25.  75.  75.  25. 100.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [44]:
g = np.empty (f.shape, dtype=str)

In [45]:
g[d == d_min] = "A"
g[(d > d_min) & (d < d_mean)] = "B"
g[d == d_mean] = "C"
g[(d > d_mean) & (d < d_max)] = "D"
g[d == d_max] = "E"

print (g)

[[['D' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'B' 'D']]

 [['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'D' 'A' 'D']
  ['B' 'D' 'D' 'B' 'E']]]
